# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04dee4b2accf2e74007b696f6076b5b221ed50e0d9cbb6b826f1d0a65fe6138564f24e20c11f73153b02f7e46773b0a7034c9aeba1e6fc12d8e2318718e536e1

test:
  secret_key_base: 09dc523a683a1d87ba052dce0449cdb0bf0cdbebe6112f965782c1e140a09db981c8159e000c8310bce82bf5fe89a19becc90961479ac2537ab9266dad56cb4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
